import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-3 p-3">
          <div className="flex gap-5">
            <Link href="/">Home</Link>
            <Link href="/no-suspense">Page with data</Link>
            <Link href="/stream">Page with Suspense stream</Link>
            <Link href="/query">React Query</Link>
          </div>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
